version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/iconitodotcom
permissions:
  - object: /var/www/iconitodotcom
    pattern: '**'
    mode: '0755'
    owner: root
    group: root 
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: deploy-scripts/start_server.sh
      timeout: 300